[project]
name = "basesplit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-anthropic>=0.3.4",
    "python-dotenv>=1.0.1",
]
